import { useEffect, useMemo, useState } from 'react';
import axios from 'axios';
import { Link } from 'react-router-dom';
import { toast } from 'react-toastify';
import './Foods.css';

export default function Foods({ url, token }) {
  const [foods,setFoods]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[category,setCategory]=useState('All'),[confirm,setConfirm]=useState(null);
  const load=async()=>{setLoading(true);setError('');try{const {data}=await axios.get(`${url}/api/food/list`);setFoods(data.data||[])}catch{setError('Unable to load food items.')}finally{setLoading(false)}};useEffect(()=>{load()},[]);
  const categories=useMemo(()=>['All',...new Set(foods.map(f=>f.category))],[foods]); const visible=foods.filter(f=>(category==='All'||f.category===category)&&f.name.toLowerCase().includes(query.toLowerCase()));
  const remove=async()=>{try{const {data}=await axios.post(`${url}/api/food/remove`,{id:confirm._id},{headers:{token}});if(!data.success)throw new Error(data.message);setFoods(foods.filter(f=>f._id!==confirm._id));toast.success(data.message);setConfirm(null)}catch(e){toast.error(e.response?.data?.message||e.message||'Unable to delete food item.')}};
  return <div><div className="page-intro"><div><h2>Menu management</h2><p>Create and maintain the food your customers can order.</p></div><Link className="primary-btn" to="/foods/new">+ Add food item</Link></div><section className="panel food-panel"><div className="filters"><input placeholder="Search food…" value={query} onChange={e=>setQuery(e.target.value)}/><select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select></div>{loading?<div className="empty-inline">Loading food items…</div>:error?<div className="empty-inline">{error}<button onClick={load}>Try again</button></div>:visible.length?<div className="food-grid">{visible.map(food=><article className="food-card" key={food._id}><img src={`${url}/images/${food.image}`} alt={food.name}/><div><span className="food-category">{food.category}</span><h3>{food.name}</h3><p>{food.description}</p><b>${Number(food.price).toFixed(2)}</b><div className="food-actions"><Link to={`/foods/${food._id}/edit`}>Edit</Link><button onClick={()=>setConfirm(food)}>Delete</button></div></div></article>)}</div>:<div className="empty-inline">No food items found. <Link to="/foods/new">Add your first item.</Link></div>}</section>{confirm&&<div className="modal-backdrop"><div className="modal"><h2>Delete food item?</h2><p>Are you sure you want to delete “{confirm.name}”? This cannot be undone.</p><div><button className="secondary-btn" onClick={()=>setConfirm(null)}>Cancel</button><button className="danger-btn" onClick={remove}>Delete</button></div></div></div>}</div>;
}
